const root=document.getElementById('app');
const KEY='team-tool-intelligence-v2';
const state=JSON.parse(localStorage.getItem(KEY)||'{}');
state.statuses=state.statuses||{};
state.lastScan=state.lastScan||null;
state.lastAutoWeekStart=state.lastAutoWeekStart||null;
let page='overview'; let filter='All'; let dateFilter='All'; let search='';
function sundayMidnightOnOrBefore(d){const nd=new Date(d);nd.setHours(0,0,0,0);nd.setDate(nd.getDate()-nd.getDay());return nd;}
function nextSundayAfter(d){const nd=sundayMidnightOnOrBefore(d);nd.setDate(nd.getDate()+7);return nd;}
function runScheduledScanIfDue(){const now=new Date();const dueWeekStart=sundayMidnightOnOrBefore(now);if(!state.lastAutoWeekStart||new Date(state.lastAutoWeekStart)<dueWeekStart){state.lastAutoWeekStart=dueWeekStart.toISOString();state.lastScan=now.toISOString();state.lastScanType='Automatic (weekly)';save();}}
runScheduledScanIfDue();
const cats=['All',...new Set(TOOLS.map(t=>t.category))];
function prettyDate(d){if(d==='All')return d;const [y,m,day]=d.split('-');return `${m}/${day}/${y}`;}
function inDateRange(u){if(!dateFilter||dateFilter==='All')return true;const [start,end]=dateFilter.split('|');return u.date>=start&&u.date<=end;}
function dateLabel(){if(!dateFilter||dateFilter==='All')return 'All dates';const [start,end]=dateFilter.split('|');return start===end?prettyDate(start):`${prettyDate(start)} – ${prettyDate(end)}`;}
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function status(u){return state.statuses[u.id]||'Needs Review';}
const TOOL_LOGOS={GWI:'gwi.com',Tubular:'tubularlabs.com',Statista:'statista.com',Brandwatch:'brandwatch.com',Meltwater:'meltwater.com',CreatorIQ:'creatoriq.com',ListenFirst:'listenfirstmedia.com',Semrush:'semrush.com',Mintel:'mintel.com',Julius:'juliusworks.com',Siftsy:'siftsy.com',ChatGPT:'chatgpt.com',Slack:'slack.com',VwD:'vwd.ai',Sprinklr:'sprinklr.com'};
const TOOL_LOGINS={GWI:'https://signin.globalwebindex.com/',Tubular:'https://app.tubularlabs.com/',Statista:'https://login.statista.com/u/login/identifier?ui_locales=en',Brandwatch:'https://app.brandwatch.com/',Meltwater:'https://www.meltwater.com/en/login',CreatorIQ:'https://app.creatoriq.com/',ListenFirst:'https://app.listenfirstmedia.com/',Semrush:'https://www.semrush.com/login/',Mintel:'https://clients.mintel.com/',Julius:'https://app.juliusworks.com/login',Siftsy:'https://app.siftsy.com/',ChatGPT:'https://chatgpt.com/auth/login/',Slack:'https://slack.com/signin',VwD:'https://app.vwd.ai/',Sprinklr:'https://app.sprinklr.com/'};
function logo(tool){const domain=TOOL_LOGOS[tool];return domain?`<img class="tool-logo" src="https://www.google.com/s2/favicons?domain=${domain}&sz=128" alt="${esc(tool)} logo" loading="lazy">`:'';}
function toolLogin(tool){return TOOL_LOGINS[tool]||`https://${TOOL_LOGOS[tool]}/`;}
function toolLoginLabel(tool){return 'Open login ↗';}
function filtered(){return UPDATES.filter(u=>(filter==='All'||u.category===filter)&&inDateRange(u)&&(!search||`${u.tool} ${u.category} ${u.title} ${u.summary} ${u.impact} ${u.overlap.join(' ')}`.toLowerCase().includes(search.toLowerCase()))).sort((a,b)=>b.date.localeCompare(a.date))}
function nav(){return `<aside><div class="brand">THE·TEAM<span>TOOL INTELLIGENCE</span><em>by Fitz 🥸</em></div><button class="nav ${page==='overview'?'on':''}" data-page="overview">Overview</button><button class="nav ${page==='updates'?'on':''}" data-page="updates">Updates</button><button class="nav ${page==='tools'?'on':''}" data-page="tools">Tools</button><button class="nav ${page==='report'?'on':''}" data-page="report">Monthly Report</button><div class="side-foot">September 2026<br><span>15 tools monitored</span></div></aside>`}
function header(title,sub){const last=state.lastScan?new Date(state.lastScan):null;const lastText=last&&!Number.isNaN(last.getTime())?last.toLocaleString([],{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}):'Never';const lastType=state.lastScanType?` (${esc(state.lastScanType)})`:'';const next=nextSundayAfter(new Date());const nextText=next.toLocaleString([],{month:'short',day:'numeric',year:'numeric'});return `<header><div><h1>${title}</h1><p>${sub}</p></div><div class="scan-wrap"><button id="scan" class="primary">↻ Run monitoring scan</button><span class="last-scan">Last run · ${lastText}${lastType}</span><span class="next-scan">Auto-scans weekly · Sun 12:00 AM · next ${nextText}</span></div></header>`}
function reliabilityFlag(u){return u.reliability==='Flagged'?'<span class="reliability-flag" title="Unverified source — review before acting">⚠ Unverified source</span>':'';}
function cards(){let arr=filtered();return `<div class="cards">${arr.map(u=>`<article class="card" data-id="${u.id}"><div class="row"><span class="tag">${esc(u.category)}</span><span class="priority ${u.priority.toLowerCase()}">${u.priority}</span></div><h3 class="tool-title">${logo(u.tool)}<span>${esc(u.tool)}</span></h3><h2>${esc(u.title)}</h2><p>${esc(u.summary)}</p>${reliabilityFlag(u)}<div class="meta"><span>${prettyDate(u.date)}</span><span class="status ${status(u).toLowerCase().replaceAll(' ','-')}">${status(u)}</span></div></article>`).join('')}</div>`}
function overview(){let hi=UPDATES.filter(u=>u.priority==='High').length; return header('Tool Intelligence','A working view of tool changes, capability overlap, and review status')+`<section class="stats"><div><b>15</b><span>Tools monitored</span></div><div><b>${UPDATES.length}</b><span>Updates tracked</span></div><div><b>${hi}</b><span>High priority</span></div><div><b>${Object.values(state.statuses).filter(x=>x==='Verified').length}</b><span>Verified</span></div></section><section class="panel"><div class="panel-head"><div><h2>Priority Updates</h2><p>Click an update to review the intelligence brief.</p></div><div class="filters">${cats.slice(0,7).map(c=>`<button class="filter ${filter===c?'sel':''}" data-filter="${esc(c)}">${esc(c)}</button>`).join('')}</div></div>${cards()}</section>`}
function updates(){let range=dateFilter==='All'?['','']:dateFilter.split('|');return header('Updates','Review the latest seeded monitoring results and triage them')+`<div class="toolbar"><input id="search" value="${esc(search)}" placeholder="Search tools or updates…"><select id="cat">${cats.map(c=>`<option ${filter===c?'selected':''}>${esc(c)}</option>`).join('')}</select><div class="date-filter"><button id="dateBtn" class="date-btn">▣ ${dateLabel()}</button><div id="datePopover" class="date-popover"><div><label>From</label><input type="date" id="dateStart" value="${range[0]||''}"></div><div><label>To</label><input type="date" id="dateEnd" value="${range[1]||''}"></div><div class="date-actions"><button id="dateClear">Clear</button><button id="dateApply" class="primary">Apply</button></div></div></div></div><section class="panel">${cards()}</section>`}
function tools(){const groups={};TOOLS.forEach(t=>(groups[t.category]||(groups[t.category]=[])).push(t));return header('Tool Registry','Click any tool to open its login page')+Object.entries(groups).map(([category,items])=>`<section class="panel tool-category-panel"><div class="category-head"><h2>${esc(category)}</h2><span>${items.length} tool${items.length===1?'':'s'}</span></div><div class="tool-grid">${items.map(t=>`<a class="tool" href="${toolLogin(t.name)}" target="_blank" rel="noopener" title="Open ${esc(t.name)} login"><div class="tool-name">${logo(t.name)}<span>${esc(t.name)}</span><span class="login-arrow">↗</span></div><div class="tool-category">${esc(t.category)}</div><small>Owner · ${esc(t.owner)} · ${esc(t.status)}</small><div class="tool-login">${toolLoginLabel(t.name)}</div></a>`).join('')}</div></section>`).join('')}
function report(){let overlap={};UPDATES.forEach(u=>u.overlap.forEach(x=>overlap[x]=(overlap[x]||0)+1));let top=Object.entries(overlap).sort((a,b)=>b[1]-a[1]).slice(0,6);return header('September 2026 Monthly Report','A concise intelligence brief for strategy and capability planning')+`<section class="report"><div class="panel"><h2>Executive readout</h2><p>AI-assisted research, social intelligence and workflow automation are the most important themes across this month’s monitored updates. The strongest strategic question is where point-tool functionality is beginning to converge with general-purpose AI.</p><h3>Top capability themes</h3>${top.map(([k,v])=>`<div class="bar"><span>${esc(k)}</span><b>${v}</b></div>`).join('')}</div><div class="panel"><h2>Recommended actions</h2><ol><li>Verify the highest-priority updates before circulating externally.</li><li>Map overlapping capabilities to existing workflows and licenses.</li><li>Identify 2–3 tools where AI functionality could change the current stack.</li><li>Keep source URLs and confidence levels attached to each intelligence record.</li></ol><button id="export" class="primary">Export brief (.txt)</button></div></section>`}
function render(){root.innerHTML=`<div class="layout">${nav()}<main>${page==='overview'?overview():page==='updates'?updates():page==='tools'?tools():report()}</main></div><div id="modal"></div>`;bind();}
function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()});document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render()});document.querySelectorAll('.card').forEach(c=>c.onclick=()=>open(+c.dataset.id));const s=document.getElementById('search');if(s)s.oninput=e=>{search=e.target.value;const wrap=document.querySelector('.cards');if(wrap){const rendered=cards();const match=rendered.match(/^<div class="cards">([\s\S]*)<\/div>$/);wrap.innerHTML=match?match[1]:'';bindCards()}};const cat=document.getElementById('cat');if(cat)cat.onchange=e=>{filter=e.target.value;render()};const dateBtn=document.getElementById('dateBtn');if(dateBtn)dateBtn.onclick=()=>document.getElementById('datePopover').classList.toggle('open');const dateApply=document.getElementById('dateApply');if(dateApply)dateApply.onclick=()=>{const start=document.getElementById('dateStart').value;const end=document.getElementById('dateEnd').value;if(start&&end&&start>end){alert('End date must be on or after start date.');return}dateFilter=start?`${start}|${end||start}`:'All';render()};const dateClear=document.getElementById('dateClear');if(dateClear)dateClear.onclick=()=>{dateFilter='All';render()};const scan=document.getElementById('scan');if(scan)scan.onclick=()=>{scan.textContent='Scanning…';scan.disabled=true;setTimeout(()=>{const runTime=new Date();state.lastScan=runTime.toISOString();state.lastScanType='Manual';save();scan.textContent='✓ Scan complete';openScanResult(runTime,'Manual');setTimeout(()=>{if(document.getElementById('scan'))render()},1400)},800)};const ex=document.getElementById('export');if(ex)ex.onclick=()=>{const text=`THE·TEAM TOOL INTELLIGENCE — SEPTEMBER 2026\n\nExecutive readout\nAI-assisted research, social intelligence and workflow automation are the dominant themes.\n\nPriority updates\n${UPDATES.filter(u=>u.priority==='High').map(u=>`- ${u.tool}: ${u.title}`).join('\n')}\n\nRecommended actions\n1. Verify priority updates.\n2. Map overlaps to workflows and licenses.\n3. Identify AI-driven stack changes.`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/plain'}));a.download='THE-TEAM-Tool-Intelligence-September-2026.txt';a.click()};}
function bindCards(){document.querySelectorAll('.card').forEach(c=>c.onclick=()=>open(+c.dataset.id));}
function reliabilityBlock(u){if(u.reliability==='Flagged'){return `<div class="reliability-box flagged"><b>⚠ Unverified source</b><p>${esc(u.reliabilityNote||'This source is not an official company channel. Verify before acting on it.')}</p></div>`}return `<div class="reliability-box reliable"><b>✓ Reliable source</b><p>Sourced from an official company channel (${esc(u.sourceType)}).</p></div>`}
function open(id){const u=UPDATES.find(x=>x.id===id);document.getElementById('modal').innerHTML=`<div class="shade"><div class="modal"><button class="close">×</button><span class="tag">${esc(u.category)}</span><h2 class="modal-tool-title">${logo(u.tool)}<span>${esc(u.tool)}</span><span> — ${esc(u.title)}</span></h2><div class="modal-date">Update date · ${prettyDate(u.date)}</div><h4>What changed</h4><p>${esc(u.summary)}</p><h4>Why it matters to THE·TEAM</h4><p>${esc(u.impact)}</p><h4>Potential overlap</h4><div>${u.overlap.map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div><div class="detail"><span>Confidence: <b>${u.confidence}</b></span><span>Priority: <b>${u.priority}</b></span><span>Status: <b>${status(u)}</b></span></div>${reliabilityBlock(u)}<a href="${u.source}" target="_blank" rel="noopener">View source ↗</a><div class="actions"><button data-status="Verified">✓ Verify</button><button data-status="Dismissed">Dismiss</button><button data-status="Needs Review">Needs Review</button></div></div></div>`;document.querySelector('.close').onclick=close;document.querySelector('.shade').onclick=e=>{if(e.target.classList.contains('shade'))close()};document.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>{state.statuses[id]=b.dataset.status;save();close();render()})}
function openScanResult(runTime,runType){const sourced=UPDATES.length;const high=UPDATES.filter(u=>u.priority==='High').length;const flagged=UPDATES.filter(u=>u.reliability==='Flagged').length;const tools=TOOLS.length;const stamp=runTime.toLocaleString([],{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'});const next=nextSundayAfter(runTime).toLocaleString([],{month:'short',day:'numeric',year:'numeric'});document.getElementById('modal').innerHTML='<div class="shade"><div class="modal scan-result"><button class="close">×</button><div class="scan-success">✓</div><h2>Monitoring scan complete</h2><p class="scan-time">'+stamp+' · '+esc(runType||'Manual')+' run</p><div class="scan-stats"><div><b>'+sourced+'</b><span>Updates sourced</span></div><div><b>'+tools+'</b><span>Tools checked</span></div><div><b>'+high+'</b><span>High priority</span></div><div><b>'+flagged+'</b><span>Flagged sources</span></div></div><p class="scan-note">The monitoring run completed successfully. Review the Updates page to triage newly surfaced intelligence. Next automatic weekly scan: '+next+' (Sun 12:00 AM).</p><button class="primary scan-done">Done</button></div></div>';document.querySelector('.scan-result .close').onclick=close;document.querySelector('.scan-done').onclick=close;document.querySelector('.shade').onclick=e=>{if(e.target.classList.contains('shade'))close()}}
function close(){document.getElementById('modal').innerHTML=''}
render();