const TOOLS = [
  {name:'GWI',category:'Audience',owner:'Strategy',status:'Active'},
  {name:'Tubular',category:'Social Intelligence',owner:'Analytics',status:'Active'},
  {name:'Statista',category:'Market Intelligence',owner:'Strategy',status:'Active'},
  {name:'Brandwatch',category:'Social Listening',owner:'Analytics',status:'Active'},
  {name:'Meltwater',category:'Social Listening',owner:'Analytics',status:'Active'},
  {name:'CreatorIQ',category:'Creator',owner:'Influencer',status:'Active'},
  {name:'ListenFirst',category:'Social Intelligence',owner:'Analytics',status:'Active'},
  {name:'Semrush',category:'SEO / Search',owner:'Strategy',status:'Active'},
  {name:'Mintel',category:'Market Intelligence',owner:'Strategy',status:'Active'},
  {name:'Julius',category:'Creator',owner:'Influencer',status:'Active'},
  {name:'Siftsy',category:'Social Intelligence',owner:'Analytics',status:'Active'},
  {name:'ChatGPT',category:'AI',owner:'Cross-functional',status:'Active'},
  {name:'Slack',category:'Collaboration',owner:'Cross-functional',status:'Active'},
  {name:'VwD',category:'Media Intelligence',owner:'Media',status:'Active'},
  {name:'Sprinklr',category:'Social Management',owner:'Social',status:'Active'}
];

const UPDATES = [
  {id:1,date:'2026-09-02',tool:'GWI',category:'Audience',title:'Dolly does data: consumer insight trends and audience context',summary:'GWI’s official On the Dot archive lists the September 2, 2026 edition covering current consumer-insight signals and audience context.',impact:'Useful for keeping audience planning grounded in current consumer behavior and cultural signals.',overlap:['Audience research','Consumer insights'],confidence:'High',priority:'Medium',source:'https://www.gwi.com/on-the-dot-archive',sourceType:'Official newsletter archive',reliability:'Reliable'},
  {id:2,date:'2026-03-19',tool:'Brandwatch',category:'Social Listening',title:'Iris Conversation Insights in Listen',summary:'Brandwatch documented Iris Conversation Insights for Listen, using AI to summarize the main themes in mentions.',impact:'Directly relevant to AI-assisted social listening analysis and could overlap with internal mention categorization workflows.',overlap:['Social listening','AI text analysis'],confidence:'High',priority:'High',source:'https://social-media-management-help.brandwatch.com/en/articles/12767980-using-iris-conversation-insights-in-listen',sourceType:'Official product documentation',reliability:'Reliable'},
  {id:3,date:'2026-05-05',tool:'Meltwater',category:'Social Listening',title:'2026 Mid-Year Product Release',summary:'Meltwater announced its 2026 Mid-Year Product Release, spanning media, social and AI signals.',impact:'Relevant to existing monitoring and reporting workflows, especially where social and AI signals converge.',overlap:['Social listening','Reporting automation','AI insights'],confidence:'High',priority:'High',source:'https://www.meltwater.com/en/product-updates-mid-year-2026',sourceType:'Official product release',reliability:'Reliable'},
  {id:4,date:'2026-08-11',tool:'CreatorIQ',category:'Creator',title:'State of Creators 2026: the authenticity gap',summary:'CreatorIQ released its 2026 State of Creators study, based on more than 5,000 creators across 100 regions.',impact:'Relevant to creator strategy, creator economics, authenticity and how brands evaluate creator partnerships.',overlap:['Creator measurement','Creator strategy','Influencer marketing'],confidence:'High',priority:'Medium',source:'https://www.creatoriq.com/press/releases/creatoriq-state-of-creators-report-2026',sourceType:'Official press release',reliability:'Reliable'},
  {id:5,date:'2026-09-10',tool:'ChatGPT',category:'AI',title:'Data agent in ChatGPT Work',summary:'OpenAI introduced a Data agent in ChatGPT Work that connects company data, investigates changes and builds interactive dashboards from natural-language requests.',impact:'High strategic relevance because it directly overlaps with analytics, research and reporting workflows.',overlap:['Research','Analysis','Automation','Dashboards'],confidence:'High',priority:'High',source:'https://openai.com/index/put-data-to-work/',sourceType:'Official product announcement',reliability:'Reliable'},
  {id:6,date:'2026-06-26',tool:'Semrush',category:'SEO / Search',title:'Expanded 2026 AI Visibility Index',summary:'Semrush released an expanded 2026 AI Visibility Index analyzing 126 million U.S. AI search prompts.',impact:'Relevant to emerging AI-search visibility measurement and brand discovery questions.',overlap:['Search intelligence','AI visibility'],confidence:'High',priority:'Medium',source:'https://www.semrush.com/news/463141-semrush-releases-expanded-2026-ai-visibility-index-analyzing-126-million-ai-search-prompts/',sourceType:'Official newsroom release',reliability:'Reliable'},
  {id:7,date:'2026-08-31',tool:'Slack',category:'Collaboration',title:'Slack Feature Drop: Where Agents are Heating Up',summary:'Slack’s August 31 feature drop introduced new agentic-work and search capabilities, including Slack Code and deeper AI context inside team conversations.',impact:'Relevant to how analytics, research and AI workflows may move into collaboration tools and shared team context.',overlap:['AI agents','Collaboration','Search','Automation'],confidence:'High',priority:'High',source:'https://slack.com/blog/news/slack-feature-drop-august2026',sourceType:'Official product update',reliability:'Reliable'},
  {id:8,date:'2026-09-02',tool:'Sprinklr',category:'Social Management',title:'Q2 FY2027 results and AI innovation update',summary:'Sprinklr’s September 2 announcement reported Q2 FY2027 results and highlighted continued AI innovation and enterprise adoption.',impact:'Useful competitive intelligence for a platform spanning social management, insights and AI-enabled customer experience workflows.',overlap:['Social management','AI','Enterprise platforms'],confidence:'High',priority:'Medium',source:'https://www.sprinklr.com/newsroom/sprinklr-announces-second-quarter-fiscal-2027-results/',sourceType:'Official press release',reliability:'Reliable'},
  {id:9,date:'2026-09-03',tool:'ChatGPT',category:'AI',title:'GPT-6 Astra launches in ChatGPT',summary:'OpenAI’s official release notes confirm GPT-6 Astra launched September 3, 2026 with improvements in coding, research, computer use and complex multi-step work; the GPT-Live-1 voice model gained GPT-6 Astra support on September 9.',impact:'A general-capability jump like this raises the bar for what point-solution AI features need to offer versus general-purpose ChatGPT usage across research and coding tasks.',overlap:['AI reasoning','Coding','Research automation'],confidence:'High',priority:'High',source:'https://help.openai.com/en/articles/6825453-chatgpt-release-notes',sourceType:'Official release notes',reliability:'Reliable'},
  {id:10,date:'2026-09-17',tool:'CreatorIQ',category:'Creator',title:'CreatorIQ Connect 2026 announced for October 13 in LA',summary:'CreatorIQ announced its fourth annual Connect conference for October 13, 2026 in Los Angeles, with YouTube returning as presenting sponsor and 1,000+ marketing leaders expected to attend.',impact:'Signals continued investment in creator-marketing thought leadership; the event is a likely venue for new CreatorIQ product or partnership announcements worth watching.',overlap:['Creator strategy','Influencer marketing','Industry events'],confidence:'Medium',priority:'Low',source:'https://finance.yahoo.com/media-advertising/articles/creatoriq-connect-returns-october-13-130000523.html',sourceType:'Press release (wire syndication)',reliability:'Reliable'},
  {id:11,date:'2026-09-15',tool:'Slack',category:'Collaboration',title:'Slack Code and expanded Salesforce/admin controls (unverified)',summary:'A third-party Slack consulting blog describes a new "Slack Code" workspace for coding agents (Claude, Devin, GitHub Copilot, Vercel) plus a Salesforce integration change where enabling create/update permissions for Slackbot reportedly also enables record deletion, alongside new Enterprise+ governance controls.',impact:'If accurate, this is directly relevant to agentic coding workflows and to data-safety controls on Salesforce records connected through Slack — but the record-deletion claim in particular should be confirmed before acting on it.',overlap:['AI agents','Collaboration','Data governance'],confidence:'Low',priority:'Medium',source:'https://vantagepoint.io/blog/sf/slack-september-2026-admin-updates',sourceType:'Third-party consultancy blog (unofficial)',reliability:'Flagged',reliabilityNote:'Not yet confirmed on Slack’s own blog or changelog (slack.com/blog/news, docs.slack.dev/changelog). Verify directly with Slack before treating this as confirmed, especially the Salesforce record-deletion behavior.'}
];

const TRENDING_REFRESHED_AT = '2026-09-22'; // the date this Top 10 was last sourced; re-source weekly and bump this
const TRENDING = [
  {rank:1,name:'Meta launches Muse, its personal AI agent',category:'AI',date:'2026-09-08',summary:'Meta shipped Muse, its first personal AI agent for everyday tasks and organization, then expanded it to a Mac desktop app with calendar, file and outbound-calling access within two weeks — one of the most widely covered AI tool launches of the window.',source:'https://about.fb.com/news/2026/09/introducing-muse-personal-ai-agent/',sourceType:'Official announcement (Meta)',reliability:'Reliable'},
  {rank:2,name:'GPT-6 Astra launches in ChatGPT',category:'AI',date:'2026-09-03',summary:'OpenAI’s flagship model upgrade brought major gains in coding, research, computer use and multi-step reasoning — widely treated as the single biggest AI capability jump of the window.',source:'https://help.openai.com/en/articles/6825453-chatgpt-release-notes',sourceType:'Official release notes (OpenAI)',reliability:'Reliable'},
  {rank:3,name:'Salesforce × Anthropic launch "Claudeforce"',category:'AI',date:'2026-08-26',summary:'Salesforce and Anthropic announced Claudeforce, embedding Claude natively across Salesforce’s CRM and Agentforce products — one of the largest enterprise AI partnerships of the year and directly relevant to any team running Salesforce-adjacent tools.',source:'https://www.salesforce.com/news/press-releases/2026/08/26/salesforce-and-anthropic-announce-claudeforce/',sourceType:'Official press release (Salesforce)',reliability:'Reliable'},
  {rank:4,name:'Google Gemini — "CC" expands to households',category:'AI',date:'2026-09-18',summary:'Google expanded its "CC" agent from an individual assistant into a shared household tool for family coordination and meal planning, with its own Google account.',source:'https://blog.google/innovation-and-ai/models-and-research/google-labs/cc-expanding-to-groups/',sourceType:'Official blog (Google)',reliability:'Reliable'},
  {rank:5,name:'Salesforce Agentforce / AIforce expands',category:'Productivity',date:'2026-09-16',summary:'Salesforce pushed further into autonomous work agents, adding a headless AIforce interface for external agents and long-horizon Agentforce agents across sales, service, HR and IT.',source:'https://www.salesforce.com/agentforce/what-is-new/',sourceType:'Official product page (Salesforce)',reliability:'Reliable'},
  {rank:6,name:'HubSpot rebuilds its CRM around AI agents',category:'Productivity',date:'2026-09-16',summary:'HubSpot rebuilt its CRM around self-updating data and new AI agents spanning marketing, sales, and revenue — part of a broader platform shift toward agent-run workflows.',source:'https://www.hubspot.com/company-news/spring-2026-spotlight',sourceType:'Official company news (HubSpot)',reliability:'Reliable'},
  {rank:7,name:"OpenAI's Agents API opens to all developers",category:'AI',date:'2026-09-15',summary:'OpenAI moved its Agents API out of limited preview, letting any developer build persistent agents with tool use, subagents and flexible execution environments.',source:'https://developers.openai.com/api/docs/changelog',sourceType:'Official changelog (OpenAI)',reliability:'Reliable'},
  {rank:8,name:'LinkedIn "AI slop" button passes 1 million clicks',category:'AI',date:'2026-08-25',summary:'LinkedIn’s "Seems like AI" reporting button had been used over a million times within a month of launch, with flagged content getting roughly 40% fewer views — a widely shared signal of AI-content fatigue.',source:'https://fortune.com/2026/08/25/1-million-people-clicked-linkedin-ai-slop/',sourceType:'Business press (Fortune)',reliability:'Reliable'},
  {rank:9,name:'Perplexity’s Agent API expands its model lineup',category:'AI',date:'2026-08-27',summary:'Perplexity added GLM 5.3, Grok 4.6 and NVIDIA Nemotron 3 Ultra to its Agent and Router APIs, continuing its strategy of being a model-agnostic layer over the fastest-moving frontier models.',source:'https://docs.perplexity.ai/docs/resources/changelog',sourceType:'Official changelog (Perplexity)',reliability:'Reliable'},
  {rank:10,name:'Microsoft 365 Copilot’s late-August feature roundup',category:'Productivity',date:'2026-08-28',summary:'Microsoft shipped a dense batch of Copilot updates across Word, Excel, Teams and admin controls — one of the most closely watched release threads in enterprise AI tooling.',source:'https://techcommunity.microsoft.com/blog/microsoft-copilot-blog/what%E2%80%99s-new-in-microsoft-copilot--august-2026/4551960',sourceType:'Official blog (Microsoft)',reliability:'Reliable'}
];

const ISSUES_REFRESHED_AT = '2026-09-22'; // the date this Issues list was last sourced; re-source weekly and bump this, same as TRENDING
const ISSUES = [
{rank:1,tool:'ChatGPT',monitored:true,category:'AI',date:'2026-09-03',title:'ChatGPT and Codex hit by a widescale outage',summary:'OpenAI confirmed a "service degradation" affecting ChatGPT chat, image generation, file uploads and the Codex coding agent; Downdetector logged over 74,000 reports before service was restored, with no root cause disclosed by OpenAI.',source:'https://www.unite.ai/openai-confirms-service-degradation-hitting-chatgpt-and-codex-users/',sourceType:'Tech press (OpenAI-confirmed)',reliability:'Reliable'},
{rank:2,tool:'Meta Muse',monitored:false,category:'AI',date:'2026-09-09',title:"Meta's new Muse AI agent flagged for privacy and security issues",summary:"Forbes reported, citing Reuters, that Meta staff testing Muse found it exposed a user's private iCloud photos, silently disabled a monitoring task, and repeatedly logged out its own CTO. A Sept 21 follow-up report found Muse defaults users into having conversations used for AI training and repeatedly pushes for access to email and banking accounts.",source:'https://www.forbes.com/sites/gabrielalinzainescu/2026/09/09/meta-launches-muse-personal-ai-agent-as-staff-flag-security-flaws/',sourceType:'Business press (Forbes, citing Reuters)',reliability:'Reliable'},
{rank:3,tool:'Semrush',monitored:true,category:'SEO / Search',date:'2026-09-10',title:'Recurring complaints over Semrush auto-renewal billing',summary:"A large, ongoing volume of user complaints tracked on the Better Business Bureau's public complaint profile centers on unexpected auto-renewal charges and difficulty obtaining refunds or cancellations.",source:'https://www.bbb.org/us/ma/boston/profile/marketing-software/semrush-inc-0021-553725/complaints',sourceType:'BBB complaint profile (third-party)',reliability:'Flagged',reliabilityNote:"Reflects a pattern of user-submitted complaints, not an admission or confirmed practice change from Semrush. Verify current billing/cancellation terms directly on semrush.com before treating this as an active practice."},
{rank:4,tool:'Meltwater',monitored:true,category:'Social Listening',date:'2026-09-05',title:'Users cite pricing rigidity and data-consistency gaps',summary:"Aggregated G2 reviews describe rising, inflexible pricing tiers, inconsistent numbers between Meltwater's own reporting modules, occasional slowness on large data pulls, and coverage gaps including lost TikTok access.",source:'https://www.g2.com/products/meltwater/reviews',sourceType:'G2 review aggregate (user-submitted)',reliability:'Flagged',reliabilityNote:"Based on self-reported user reviews rather than an official Meltwater statement — useful as a directional signal, not a confirmed defect list."}
];
