const TOOLS = [
  {name:'GWI',category:'Audience',owner:'Strategy',status:'Active'},
  {name:'Tubular',category:'Social Intelligence',owner:'Analytics',status:'Active'},
  {name:'Statista',category:'Market Intelligence',owner:'Strategy',status:'Active'},
  {name:'Brandwatch',category:'Social Listening',owner:'Analytics',status:'Active'},
  {name:'Meltwater',category:'Social Listening',owner:'Analytics',status:'Active'},
  {name:'CreatorIQ',category:'Creator',owner:'Influencer',status:'Active'},
  {name:'ListenFirst',category:'Social Intelligence',owner:'Analytics',status:'Active'},
  {name:'Semrush',category:'SEO / Search',owner:'Strategy',status:'Active'},
  {name:'Mintel',category:'Market Intelligence',owner:'Strategy',status:'Active'},
  {name:'Julius',category:'Creator',owner:'Influencer',status:'Active'},
  {name:'Siftsy',category:'Social Intelligence',owner:'Analytics',status:'Active'},
  {name:'ChatGPT',category:'AI',owner:'Cross-functional',status:'Active'},
  {name:'Slack',category:'Collaboration',owner:'Cross-functional',status:'Active'},
  {name:'VwD',category:'Media Intelligence',owner:'Media',status:'Active'},
  {name:'Sprinklr',category:'Social Management',owner:'Social',status:'Active'}
];

const UPDATES = [
  {id:1,date:'2026-09-02',tool:'GWI',category:'Audience',title:'Dolly does data: consumer insight trends and audience context',summary:'GWI’s official On the Dot archive lists the September 2, 2026 edition covering current consumer-insight signals and audience context.',impact:'Useful for keeping audience planning grounded in current consumer behavior and cultural signals.',overlap:['Audience research','Consumer insights'],confidence:'High',priority:'Medium',source:'https://www.gwi.com/on-the-dot-archive',sourceType:'Official newsletter archive',reliability:'Reliable'},
  {id:2,date:'2026-03-19',tool:'Brandwatch',category:'Social Listening',title:'Iris Conversation Insights in Listen',summary:'Brandwatch documented Iris Conversation Insights for Listen, using AI to summarize the main themes in mentions.',impact:'Directly relevant to AI-assisted social listening analysis and could overlap with internal mention categorization workflows.',overlap:['Social listening','AI text analysis'],confidence:'High',priority:'High',source:'https://social-media-management-help.brandwatch.com/en/articles/12767980-using-iris-conversation-insights-in-listen',sourceType:'Official product documentation',reliability:'Reliable'},
  {id:3,date:'2026-05-05',tool:'Meltwater',category:'Social Listening',title:'2026 Mid-Year Product Release',summary:'Meltwater announced its 2026 Mid-Year Product Release, spanning media, social and AI signals.',impact:'Relevant to existing monitoring and reporting workflows, especially where social and AI signals converge.',overlap:['Social listening','Reporting automation','AI insights'],confidence:'High',priority:'High',source:'https://www.meltwater.com/en/product-updates-mid-year-2026',sourceType:'Official product release',reliability:'Reliable'},
  {id:4,date:'2026-08-11',tool:'CreatorIQ',category:'Creator',title:'State of Creators 2026: the authenticity gap',summary:'CreatorIQ released its 2026 State of Creators study, based on more than 5,000 creators across 100 regions.',impact:'Relevant to creator strategy, creator economics, authenticity and how brands evaluate creator partnerships.',overlap:['Creator measurement','Creator strategy','Influencer marketing'],confidence:'High',priority:'Medium',source:'https://www.creatoriq.com/press/releases/creatoriq-state-of-creators-report-2026',sourceType:'Official press release',reliability:'Reliable'},
  {id:5,date:'2026-09-10',tool:'ChatGPT',category:'AI',title:'Data agent in ChatGPT Work',summary:'OpenAI introduced a Data agent in ChatGPT Work that connects company data, investigates changes and builds interactive dashboards from natural-language requests.',impact:'High strategic relevance because it directly overlaps with analytics, research and reporting workflows.',overlap:['Research','Analysis','Automation','Dashboards'],confidence:'High',priority:'High',source:'https://openai.com/index/put-data-to-work/',sourceType:'Official product announcement',reliability:'Reliable'},
  {id:6,date:'2026-06-26',tool:'Semrush',category:'SEO / Search',title:'Expanded 2026 AI Visibility Index',summary:'Semrush released an expanded 2026 AI Visibility Index analyzing 126 million U.S. AI search prompts.',impact:'Relevant to emerging AI-search visibility measurement and brand discovery questions.',overlap:['Search intelligence','AI visibility'],confidence:'High',priority:'Medium',source:'https://www.semrush.com/news/463141-semrush-releases-expanded-2026-ai-visibility-index-analyzing-126-million-ai-search-prompts/',sourceType:'Official newsroom release',reliability:'Reliable'},
  {id:7,date:'2026-08-31',tool:'Slack',category:'Collaboration',title:'Slack Feature Drop: Where Agents are Heating Up',summary:'Slack’s August 31 feature drop introduced new agentic-work and search capabilities, including Slack Code and deeper AI context inside team conversations.',impact:'Relevant to how analytics, research and AI workflows may move into collaboration tools and shared team context.',overlap:['AI agents','Collaboration','Search','Automation'],confidence:'High',priority:'High',source:'https://slack.com/blog/news/slack-feature-drop-august2026',sourceType:'Official product update',reliability:'Reliable'},
  {id:8,date:'2026-09-02',tool:'Sprinklr',category:'Social Management',title:'Q2 FY2027 results and AI innovation update',summary:'Sprinklr’s September 2 announcement reported Q2 FY2027 results and highlighted continued AI innovation and enterprise adoption.',impact:'Useful competitive intelligence for a platform spanning social management, insights and AI-enabled customer experience workflows.',overlap:['Social management','AI','Enterprise platforms'],confidence:'High',priority:'Medium',source:'https://www.sprinklr.com/newsroom/sprinklr-announces-second-quarter-fiscal-2027-results/',sourceType:'Official press release',reliability:'Reliable'},
  {id:9,date:'2026-09-03',tool:'ChatGPT',category:'AI',title:'GPT-6 Astra launches in ChatGPT',summary:'OpenAI’s official release notes confirm GPT-6 Astra launched September 3, 2026 with improvements in coding, research, computer use and complex multi-step work; the GPT-Live-1 voice model gained GPT-6 Astra support on September 9.',impact:'A general-capability jump like this raises the bar for what point-solution AI features need to offer versus general-purpose ChatGPT usage across research and coding tasks.',overlap:['AI reasoning','Coding','Research automation'],confidence:'High',priority:'High',source:'https://help.openai.com/en/articles/6825453-chatgpt-release-notes',sourceType:'Official release notes',reliability:'Reliable'},
  {id:10,date:'2026-09-17',tool:'CreatorIQ',category:'Creator',title:'CreatorIQ Connect 2026 announced for October 13 in LA',summary:'CreatorIQ announced its fourth annual Connect conference for October 13, 2026 in Los Angeles, with YouTube returning as presenting sponsor and 1,000+ marketing leaders expected to attend.',impact:'Signals continued investment in creator-marketing thought leadership; the event is a likely venue for new CreatorIQ product or partnership announcements worth watching.',overlap:['Creator strategy','Influencer marketing','Industry events'],confidence:'Medium',priority:'Low',source:'https://finance.yahoo.com/media-advertising/articles/creatoriq-connect-returns-october-13-130000523.html',sourceType:'Press release (wire syndication)',reliability:'Reliable'},
  {id:11,date:'2026-09-15',tool:'Slack',category:'Collaboration',title:'Slack Code and expanded Salesforce/admin controls (unverified)',summary:'A third-party Slack consulting blog describes a new "Slack Code" workspace for coding agents (Claude, Devin, GitHub Copilot, Vercel) plus a Salesforce integration change where enabling create/update permissions for Slackbot reportedly also enables record deletion, alongside new Enterprise+ governance controls.',impact:'If accurate, this is directly relevant to agentic coding workflows and to data-safety controls on Salesforce records connected through Slack — but the record-deletion claim in particular should be confirmed before acting on it.',overlap:['AI agents','Collaboration','Data governance'],confidence:'Low',priority:'Medium',source:'https://vantagepoint.io/blog/sf/slack-september-2026-admin-updates',sourceType:'Third-party consultancy blog (unofficial)',reliability:'Flagged',reliabilityNote:'Not yet confirmed on Slack’s own blog or changelog (slack.com/blog/news, docs.slack.dev/changelog). Verify directly with Slack before treating this as confirmed, especially the Salesforce record-deletion behavior.'}
];
